/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xboxcontroller;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Root10
 */
public class RoverController extends javax.swing.JFrame {

    JLabel currentLabel_RoverRun ;
    JLabel currentLabel_RoverActuator ;
    /**
     * Creates new form RoverController
     */
    public RoverController() {
        initComponents();
        //setLocationRelativeTo(null);
        setTitle("Rovar Controller");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        currentLabel_RoverRun = RoverRun_W;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        RoverActuator_1 = new javax.swing.JLabel();
        RoverActuator_2 = new javax.swing.JLabel();
        RoverActuator_3 = new javax.swing.JLabel();
        RoverActuator_4 = new javax.swing.JLabel();
        RoverActuator_5 = new javax.swing.JLabel();
        RoverActuator_6 = new javax.swing.JLabel();
        RoverActuator_7 = new javax.swing.JLabel();
        RoverActuator_8 = new javax.swing.JLabel();
        RoverActuator_9 = new javax.swing.JLabel();
        RoverActuator_10 = new javax.swing.JLabel();
        RoverActuator_11 = new javax.swing.JLabel();
        RoverActuator_12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        RoverRun_W = new javax.swing.JLabel();
        RoverRun_D = new javax.swing.JLabel();
        RoverRun_A = new javax.swing.JLabel();
        RoverRun_S = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ROVER CONTROLLER");

        jPanel1.setPreferredSize(new java.awt.Dimension(399, 378));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Down");

        RoverActuator_1.setBackground(new java.awt.Color(255, 255, 255));
        RoverActuator_1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RoverActuator_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoverActuator_1.setText("1");
        RoverActuator_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        RoverActuator_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RoverActuator_1.setOpaque(true);
        RoverActuator_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RoverActuator_1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RoverActuator_1MouseReleased(evt);
            }
        });

        RoverActuator_2.setBackground(new java.awt.Color(255, 255, 255));
        RoverActuator_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RoverActuator_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoverActuator_2.setText("2");
        RoverActuator_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        RoverActuator_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RoverActuator_2.setOpaque(true);
        RoverActuator_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RoverActuator_2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RoverActuator_2MouseReleased(evt);
            }
        });

        RoverActuator_3.setBackground(new java.awt.Color(255, 255, 255));
        RoverActuator_3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RoverActuator_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoverActuator_3.setText("3");
        RoverActuator_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        RoverActuator_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RoverActuator_3.setOpaque(true);
        RoverActuator_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RoverActuator_3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RoverActuator_3MouseReleased(evt);
            }
        });

        RoverActuator_4.setBackground(new java.awt.Color(255, 255, 255));
        RoverActuator_4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RoverActuator_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoverActuator_4.setText("4");
        RoverActuator_4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        RoverActuator_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RoverActuator_4.setOpaque(true);
        RoverActuator_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RoverActuator_4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RoverActuator_4MouseReleased(evt);
            }
        });

        RoverActuator_5.setBackground(new java.awt.Color(255, 255, 255));
        RoverActuator_5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RoverActuator_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoverActuator_5.setText("5");
        RoverActuator_5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        RoverActuator_5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RoverActuator_5.setOpaque(true);
        RoverActuator_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RoverActuator_5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RoverActuator_5MouseReleased(evt);
            }
        });

        RoverActuator_6.setBackground(new java.awt.Color(255, 255, 255));
        RoverActuator_6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RoverActuator_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoverActuator_6.setText("6");
        RoverActuator_6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        RoverActuator_6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RoverActuator_6.setOpaque(true);
        RoverActuator_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RoverActuator_6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RoverActuator_6MouseReleased(evt);
            }
        });

        RoverActuator_7.setBackground(new java.awt.Color(255, 255, 255));
        RoverActuator_7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RoverActuator_7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoverActuator_7.setText("1");
        RoverActuator_7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        RoverActuator_7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RoverActuator_7.setOpaque(true);
        RoverActuator_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RoverActuator_7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RoverActuator_7MouseReleased(evt);
            }
        });

        RoverActuator_8.setBackground(new java.awt.Color(255, 255, 255));
        RoverActuator_8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RoverActuator_8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoverActuator_8.setText("2");
        RoverActuator_8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        RoverActuator_8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RoverActuator_8.setOpaque(true);
        RoverActuator_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RoverActuator_8MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RoverActuator_8MouseReleased(evt);
            }
        });

        RoverActuator_9.setBackground(new java.awt.Color(255, 255, 255));
        RoverActuator_9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RoverActuator_9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoverActuator_9.setText("3");
        RoverActuator_9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        RoverActuator_9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RoverActuator_9.setOpaque(true);
        RoverActuator_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RoverActuator_9MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RoverActuator_9MouseReleased(evt);
            }
        });

        RoverActuator_10.setBackground(new java.awt.Color(255, 255, 255));
        RoverActuator_10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RoverActuator_10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoverActuator_10.setText("4");
        RoverActuator_10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        RoverActuator_10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RoverActuator_10.setOpaque(true);
        RoverActuator_10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RoverActuator_10MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RoverActuator_10MouseReleased(evt);
            }
        });

        RoverActuator_11.setBackground(new java.awt.Color(255, 255, 255));
        RoverActuator_11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RoverActuator_11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoverActuator_11.setText("5");
        RoverActuator_11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        RoverActuator_11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RoverActuator_11.setOpaque(true);
        RoverActuator_11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RoverActuator_11MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RoverActuator_11MouseReleased(evt);
            }
        });

        RoverActuator_12.setBackground(new java.awt.Color(255, 255, 255));
        RoverActuator_12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RoverActuator_12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoverActuator_12.setText("6");
        RoverActuator_12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        RoverActuator_12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RoverActuator_12.setOpaque(true);
        RoverActuator_12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RoverActuator_12MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RoverActuator_12MouseReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ROVER ACTUATOR");

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Up");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RoverActuator_1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(RoverActuator_2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(RoverActuator_3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RoverActuator_4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(RoverActuator_5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(RoverActuator_6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RoverActuator_7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(RoverActuator_8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(RoverActuator_9, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(RoverActuator_10, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(RoverActuator_11, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(RoverActuator_12, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 27, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RoverActuator_2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RoverActuator_1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RoverActuator_3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RoverActuator_5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RoverActuator_4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RoverActuator_6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RoverActuator_8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RoverActuator_7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RoverActuator_9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RoverActuator_11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RoverActuator_10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RoverActuator_12, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ROVER RUN");

        RoverRun_W.setBackground(new java.awt.Color(255, 255, 255));
        RoverRun_W.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RoverRun_W.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoverRun_W.setText("W");
        RoverRun_W.setToolTipText("");
        RoverRun_W.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        RoverRun_W.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RoverRun_W.setFocusable(false);
        RoverRun_W.setOpaque(true);

        RoverRun_D.setBackground(new java.awt.Color(255, 255, 255));
        RoverRun_D.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RoverRun_D.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoverRun_D.setText("D");
        RoverRun_D.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        RoverRun_D.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RoverRun_D.setOpaque(true);

        RoverRun_A.setBackground(new java.awt.Color(255, 255, 255));
        RoverRun_A.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RoverRun_A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoverRun_A.setText("A");
        RoverRun_A.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        RoverRun_A.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RoverRun_A.setOpaque(true);

        RoverRun_S.setBackground(new java.awt.Color(255, 255, 255));
        RoverRun_S.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RoverRun_S.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoverRun_S.setText("S");
        RoverRun_S.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        RoverRun_S.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RoverRun_S.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Rover all controlls");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"W", "Go forward", "Keyboard"},
                {"S", "Go back", "Keyboard"},
                {"A", "Go Left", "Keyboard"},
                {"D", "Go Right", "Keyboard"}
            },
            new String [] {
                "Controll", "Work", "Controll By"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTable1.setDropMode(javax.swing.DropMode.ON);
        jTable1.setEnabled(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RoverRun_S, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoverRun_W, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(RoverRun_A, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RoverRun_D, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addComponent(RoverRun_W, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoverRun_D, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoverRun_A, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RoverRun_S, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
       String key = evt.getKeyChar()+"";
       this.AllKeyPreesAction_Run(key);
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        currentLabel_RoverRun.setBackground(Color.WHITE);
    }//GEN-LAST:event_formKeyReleased

    private void RoverActuator_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoverActuator_1MousePressed
        // TODO add your handling code here:
        RoverActuator_1.setBackground(Color.red);
    }//GEN-LAST:event_RoverActuator_1MousePressed

    private void RoverActuator_1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoverActuator_1MouseReleased
        // TODO add your handling code here:
        RoverActuator_1.setBackground(Color.WHITE);
    }//GEN-LAST:event_RoverActuator_1MouseReleased

    private void RoverActuator_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoverActuator_2MousePressed
        // TODO add your handling code here:
        RoverActuator_2.setBackground(Color.red);
    }//GEN-LAST:event_RoverActuator_2MousePressed

    private void RoverActuator_2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoverActuator_2MouseReleased
        // TODO add your handling code here:
         RoverActuator_2.setBackground(Color.WHITE);
    }//GEN-LAST:event_RoverActuator_2MouseReleased

    private void RoverActuator_3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoverActuator_3MousePressed
        // TODO add your handling code here:
        RoverActuator_3.setBackground(Color.RED);
    }//GEN-LAST:event_RoverActuator_3MousePressed

    private void RoverActuator_3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoverActuator_3MouseReleased
        // TODO add your handling code here:
        RoverActuator_3.setBackground(Color.WHITE);
    }//GEN-LAST:event_RoverActuator_3MouseReleased

    private void RoverActuator_4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoverActuator_4MousePressed
        // TODO add your handling code here:
        RoverActuator_4.setBackground(Color.RED);
    }//GEN-LAST:event_RoverActuator_4MousePressed

    private void RoverActuator_4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoverActuator_4MouseReleased
        // TODO add your handling code here:
        RoverActuator_4.setBackground(Color.WHITE);
    }//GEN-LAST:event_RoverActuator_4MouseReleased

    private void RoverActuator_5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoverActuator_5MousePressed
        // TODO add your handling code here:
        RoverActuator_5.setBackground(Color.RED);
    }//GEN-LAST:event_RoverActuator_5MousePressed

    private void RoverActuator_5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoverActuator_5MouseReleased
        // TODO add your handling code here:
        RoverActuator_5.setBackground(Color.WHITE);
    }//GEN-LAST:event_RoverActuator_5MouseReleased

    private void RoverActuator_6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoverActuator_6MousePressed
        // TODO add your handling code here:
        RoverActuator_6.setBackground(Color.RED);
    }//GEN-LAST:event_RoverActuator_6MousePressed

    private void RoverActuator_6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoverActuator_6MouseReleased
        // TODO add your handling code here:
        RoverActuator_6.setBackground(Color.WHITE);
    }//GEN-LAST:event_RoverActuator_6MouseReleased

    private void RoverActuator_7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoverActuator_7MousePressed
        // TODO add your handling code here:
        RoverActuator_7.setBackground(Color.RED);
    }//GEN-LAST:event_RoverActuator_7MousePressed

    private void RoverActuator_7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoverActuator_7MouseReleased
        // TODO add your handling code here:
        RoverActuator_7.setBackground(Color.WHITE);
    }//GEN-LAST:event_RoverActuator_7MouseReleased

    private void RoverActuator_8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoverActuator_8MousePressed
        // TODO add your handling code here:
        RoverActuator_8.setBackground(Color.RED);
    }//GEN-LAST:event_RoverActuator_8MousePressed

    private void RoverActuator_8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoverActuator_8MouseReleased
        // TODO add your handling code here:
        RoverActuator_8.setBackground(Color.WHITE);
    }//GEN-LAST:event_RoverActuator_8MouseReleased

    private void RoverActuator_9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoverActuator_9MousePressed
        // TODO add your handling code here:
        RoverActuator_9.setBackground(Color.RED);
    }//GEN-LAST:event_RoverActuator_9MousePressed

    private void RoverActuator_9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoverActuator_9MouseReleased
        // TODO add your handling code here:
        RoverActuator_9.setBackground(Color.WHITE);
    }//GEN-LAST:event_RoverActuator_9MouseReleased

    private void RoverActuator_10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoverActuator_10MousePressed
        // TODO add your handling code here:
        RoverActuator_10.setBackground(Color.RED);
    }//GEN-LAST:event_RoverActuator_10MousePressed

    private void RoverActuator_10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoverActuator_10MouseReleased
        // TODO add your handling code here:
        RoverActuator_10.setBackground(Color.WHITE);
    }//GEN-LAST:event_RoverActuator_10MouseReleased

    private void RoverActuator_11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoverActuator_11MousePressed
        // TODO add your handling code here:
        RoverActuator_11.setBackground(Color.RED);
       
    }//GEN-LAST:event_RoverActuator_11MousePressed

    private void RoverActuator_11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoverActuator_11MouseReleased
        // TODO add your handling code here:
         RoverActuator_11.setBackground(Color.WHITE);
    }//GEN-LAST:event_RoverActuator_11MouseReleased

    private void RoverActuator_12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoverActuator_12MousePressed
        // TODO add your handling code here:
        RoverActuator_12.setBackground(Color.RED);
    }//GEN-LAST:event_RoverActuator_12MousePressed

    private void RoverActuator_12MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoverActuator_12MouseReleased
        // TODO add your handling code here:
         RoverActuator_12.setBackground(Color.WHITE);
    }//GEN-LAST:event_RoverActuator_12MouseReleased

    
    
    public void AllKeyPreesAction_Run(String key){
        if (key.endsWith("w") || key.equals("W")) {
            currentLabel_RoverRun.setBackground(Color.WHITE);
            new AllControlls().Press_W();
            currentLabel_RoverRun = RoverRun_W;
            currentLabel_RoverRun.setBackground(Color.red);
        }
        if (key.endsWith("s") || key.equals("S")) {
            currentLabel_RoverRun.setBackground(Color.WHITE);
            new AllControlls().Press_S();
            currentLabel_RoverRun = RoverRun_S;
            currentLabel_RoverRun.setBackground(Color.red);
        }
        if (key.endsWith("a") || key.equals("A")) {
            currentLabel_RoverRun.setBackground(Color.WHITE);
            new AllControlls().Press_A();
            currentLabel_RoverRun = RoverRun_A;
            currentLabel_RoverRun.setBackground(Color.red);
        }
        if (key.endsWith("d") || key.equals("D")) {
            currentLabel_RoverRun.setBackground(Color.WHITE);
            new AllControlls().Press_D();
            currentLabel_RoverRun = RoverRun_D;
            currentLabel_RoverRun.setBackground(Color.red);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoverController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoverController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoverController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoverController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoverController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RoverActuator_1;
    private javax.swing.JLabel RoverActuator_10;
    private javax.swing.JLabel RoverActuator_11;
    private javax.swing.JLabel RoverActuator_12;
    private javax.swing.JLabel RoverActuator_2;
    private javax.swing.JLabel RoverActuator_3;
    private javax.swing.JLabel RoverActuator_4;
    private javax.swing.JLabel RoverActuator_5;
    private javax.swing.JLabel RoverActuator_6;
    private javax.swing.JLabel RoverActuator_7;
    private javax.swing.JLabel RoverActuator_8;
    private javax.swing.JLabel RoverActuator_9;
    private javax.swing.JLabel RoverRun_A;
    private javax.swing.JLabel RoverRun_D;
    private javax.swing.JLabel RoverRun_S;
    private javax.swing.JLabel RoverRun_W;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
